<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFfHC4J4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFfHC4J4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFfHC4J4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFfHC4J4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFfHC4J4\App_KernelDevDebugContainer([
    'container.build_hash' => 'FfHC4J4',
    'container.build_id' => 'ac480335',
    'container.build_time' => 1615377176,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFfHC4J4');
