<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLILx9Mh\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLILx9Mh/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLILx9Mh.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLILx9Mh\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLILx9Mh\App_KernelDevDebugContainer([
    'container.build_hash' => 'LILx9Mh',
    'container.build_id' => '6e03f3b9',
    'container.build_time' => 1615465065,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLILx9Mh');
